[project]
name = "app"
version = "0.1.0"
description = ""
authors = [
  { name = "Marcus Schiesser", email = "mail@marcusschiesser.de" }
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "llama-index>=0.12.1",
    "llama-parse>=0.6.21,<0.7.0",
    "fastapi[standard]>=0.109.1",
    "uvicorn>=0.23.2",
    "python-dotenv>=1.0.0",
    "pydantic>=2.10",
    "aiostream>=0.5.2",
    "cachetools>=5.3.3",
    "rich>=13.9.4",
]

[project.optional-dependencies]
dev = [
    "mypy>=1.8.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
]

[project.scripts]
generate = "app.engine.generate:generate_datasource"
dev = "run:dev" # Starts the app in dev mode
prod = "run:prod" # Starts the app in prod mode
build = "run:build" # Builds the frontend assets and copies them to the static directory

[build-system]
requires = [ "hatchling>=1.24" ]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.11"
plugins = "pydantic.mypy"
exclude = [ "tests", "venv", ".venv", "output", "config" ]
check_untyped_defs = true
warn_unused_ignores = false
show_error_codes = true
namespace_packages = true
ignore_missing_imports = true
follow_imports = "silent"
implicit_optional = true
strict_optional = false
disable_error_code = ["return-value", "assignment"]

[[tool.mypy.overrides]]
module = "app.*"
ignore_missing_imports = false
