name: Release llama-index-server

on:
  push:
    branches:
      - main
    paths:
      - "python/llama-index-server/**"
      - ".github/workflows/release_llama_index_server.yml"
  pull_request:
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/llama-index-server
    if: |
      github.event_name == 'push' && 
      !startsWith(github.ref, 'refs/heads/release/llama-index-server-v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Bump patch version
        run: |
          poetry version patch
          git add pyproject.toml
          git commit -m "chore(release): bump version to $(poetry version -s)"

      - name: Get current version
        id: get_version
        run: |
          version=$(poetry version -s)
          echo "current_version=${version}" >> "$GITHUB_OUTPUT"

      - name: Create Release PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Release: llama-index-server v${{ steps.get_version.outputs.current_version }}"
          title: "Release: llama-index-server v${{ steps.get_version.outputs.current_version }}"
          body: |
            This PR was automatically created to release a new version of the llama-index-server package.

            Version: ${{ steps.get_version.outputs.current_version }}

            Please review the changes and merge to trigger the release.
          branch: release/llama-index-server-v${{ steps.get_version.outputs.current_version }}
          base: main
          labels: release, llama-index-server

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/llama-index-server
    if: |
      github.event_name == 'pull_request' && 
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.title, 'Release: llama-index-server') &&
      startsWith(github.event.pull_request.head.ref, 'release/llama-index-server-v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Get current version
        id: get_version
        run: |
          version=$(poetry version -s)
          echo "current_version=${version}" >> "$GITHUB_OUTPUT"

      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v2.1
        with:
          python_version: "3.11"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          package_directory: "python/llama-index-server"
          poetry_install_options: "--without dev"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: llama-index-server-v${{ steps.get_version.outputs.current_version }}
          name: "llama-index-server v${{ steps.get_version.outputs.current_version }}"
          body: |
            Release of llama-index-server v${{ steps.get_version.outputs.current_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
